#!/bin/bash

BUILDLIST=(
	util.js
	class.js
	event.js
	base.js
	model.js
	collection.js
	adapter.js
	controller.js
	router.js
	relational.js
	filtercollection.js
);

echo -n '' > composer.js
for file in "${BUILDLIST[@]}"; do
	cat src/$file >> composer.js
done

