#!/bin/bash

target=$1

if [ "${target}" == "" ]; then
	target="browser"
fi

case "${target}" in
	"browser")
		out=composer.js
		buildlist=(
			util.js
			class.js
			event.js
			base.js
			model.js
			collection.js
			adapter.js
			controller.js
			listcontroller.js
			router.js
			relational.js
			filtercollection.js
		)
		min="yes"
		;;
	"node")
		out=loader.js
		buildlist=(
			util.js
			class.js
			event.js
			base.js
			model.js
			collection.js
			relational.js
			filtercollection.js
		)
		;;
esac

if [ "${out}" == "" ]; then
	echo "Usage: $0 <browser|node>"
	exit 1
fi

echo "Remember to run me *after* changing version in package.json"
sleep 1
version=$(cat package.json | grep '"version":' | awk '{print $2}' | sed 's|[^0-9a-z\._-]||g')

echo -n '' > "${out}"
for file in "${buildlist[@]}"; do
	cat src/$file >> "${out}"
done
echo "Setting version => ${version}"
sed -i "s|version: 'GITHEAD'|version: '${version}'|" ${out}

read -r -d '' COPYRIGHT <<EOFLOL
/*
 * Copyright (c) 2011, Lyon Bros Enterprises, LLC. (http://www.lyonbros.com)
 *
 * Licensed under The MIT License.
 * Redistributions of files must retain the above copyright notice.
 */
EOFLOL
if [ "${min}" == "yes" ]; then
	minfile="$(basename "${out}" .js).min.js"
	echo -n "$COPYRIGHT" > "${minfile}"
	cat "${out}" | jsmin >> "${minfile}"
fi

